#!/bin/bash
#---------------init event for item_menu_information_remove="Удаление программ" menu-------------------------------
declare -A event_menu
event_menu["$item_menu_information_remove"]="run_menu ${item_menu_remove_apps[@]}"
event_menu["$item_menu_remove_r7"]="remove_app 'r7-office' "
event_menu["$item_menu_remove_edge"]="remove_app 'microsoft-edge-stable' "
event_menu["$item_menu_remove_mypaint"]="remove_app 'mypaint' "
event_menu["$item_menu_remove_onlyoffice"]="remove_app 'onlyoffice-desktopeditors' "
event_menu["$item_menu_remove_pascalABC"]="remove_app 'pascalabc' "
event_menu["$item_menu_remove_pinta"]="remove_app 'pinta' "
event_menu["$item_menu_remove_pycharm"]="remove_app 'pycharm' "
event_menu["$item_menu_remove_rudesktop"]="remove_app 'rudesktop-astra' "
event_menu["$item_menu_remove_skype"]="remove_app 'skypeforlinux' "
event_menu["$item_menu_remove_sublime"]="remove_app 'sublime-text' "
event_menu["$item_menu_remove_telegram"]="remove_app 'telegram' "
event_menu["$item_menu_remove_viber"]="remove_app 'viber' "
event_menu["$item_menu_remove_virtualbox"]="remove_app 'virtualbox-7.0' "
event_menu["$item_menu_remove_whatsapp"]="remove_app 'whatsapp' "
event_menu["$item_menu_remove_wps"]="remove_app 'wps-office' "
event_menu["$item_menu_remove_code"]="remove_app 'code' "
event_menu["$item_menu_remove_yandex"]="remove_app 'yandex-browser-stable' "
event_menu["$item_menu_remove_remina"]="remove_app 'remmina' "
event_menu["$item_menu_remove_xrdp"]="remove_app 'xrdp' "
event_menu["$item_menu_remove_seahorse"]="remove_app 'seahorse' "