#!/bin/bash
#---------------init event for item_menu_information_install="Установка программ" menu-------------------------------
declare -A event_menu
event_menu["$item_menu_information_install"]="run_menu ${item_menu_install_apps[@]}"
event_menu["$item_menu_install_kaspersky"]="kaspersky"
event_menu["$item_menu_install_finereader"]="finereader"
event_menu["$item_menu_install_workbench"]="workbench"
event_menu["$item_menu_install_xampp"]="xampp"
event_menu["$item_menu_install_Anaconda"]="anaconda"
event_menu["$item_menu_install_1c"]="1c_install"
event_menu["$item_menu_install_dinfo_19"]="dinfo_19"
event_menu["$item_menu_install_dinfo_22"]="dinfo_22"
event_menu["$item_menu_install_crypto1290"]="crypto1290"
event_menu["$item_menu_install_crypto1145"]="crypto1145"
event_menu["$item_menu_install_art_editor"]="fonts install_apps"
event_menu["$item_menu_install_unityhub"]="install_apps"
event_menu["$item_menu_install_pdf_editor"]="install_apps"
event_menu["$item_menu_install_edge"]="install_apps"
event_menu["$item_menu_install_mypaint"]="install_apps"
event_menu["$item_menu_install_onlyoffice"]="install_apps"
event_menu["$item_menu_install_pascalABC"]="install_apps"
event_menu["$item_menu_install_pinta"]="install_apps"
event_menu["$item_menu_install_pycharm"]="install_apps"
event_menu["$item_menu_install_skype"]="install_apps"
event_menu["$item_menu_install_sublime"]="install_apps"
event_menu["$item_menu_install_telegram"]="install_apps"
event_menu["$item_menu_install_viber"]="install_apps"
event_menu["$item_menu_install_virtualbox"]="install_virtualbox"
event_menu["$item_menu_install_whatsapp"]="install_apps"
event_menu["$item_menu_install_wps"]="install_apps"
event_menu["$item_menu_install_code"]="install_apps"
event_menu["$item_menu_install_notepadplus"]="install_apps"
event_menu["$item_menu_install_yandex"]="install_app_repo"
event_menu["$item_menu_install_remina"]="install_app_repo"
event_menu["$item_menu_install_xrdp"]="install_app_repo"
event_menu["$item_menu_install_scan"]="install_app_repo"
event_menu["$item_menu_install_seahorse"]="install_app_repo"


