#!/bin/bash
# #-------------init menu event for item_menu_information_install ----------------------

export item_menu_remove_r7="p7-office"
export item_menu_remove_edge="Microsoft-edge"
export item_menu_remove_mypaint="my-paint"
export item_menu_remove_onlyoffice="onlyoffice-desktop"
export item_menu_remove_pascalABC="PascalABC"
export item_menu_remove_pinta="Pinta"
export item_menu_remove_pycharm="Pycharm"
export item_menu_remove_rudesktop="Rudesktop"
export item_menu_remove_skype="Skype"
export item_menu_remove_sublime="Sublime"
export item_menu_remove_telegram="Telegram"
export item_menu_remove_viber="Viber"
export item_menu_remove_virtualbox="Virtualbox"
export item_menu_remove_whatsapp="Whatsapp"
export item_menu_remove_wps="Wps-office"
export item_menu_remove_code="VScode"
export item_menu_remove_notepadplus="Notepadplus"
export item_menu_remove_yandex="Yandex-browser-stable"
export item_menu_remove_remina="Remmina"
export item_menu_remove_xrdp="Xrdp"
export item_menu_remove_seahorse="Seahorse"
export item_menu_remove_apps=("\"$item_menu_remove_r7\"" "\"$item_menu_remove_edge\"" "\"$item_menu_remove_mypaint\"" "\"$item_menu_remove_onlyoffice\"" "\"$item_menu_remove_pascalABC\"" "\"$item_menu_remove_pinta\"" "\"$item_menu_remove_pycharm\"" "\"$item_menu_remove_rudesktop\"" "\"$item_menu_remove_skype\"" "\"$item_menu_remove_sublime\"" "\"$item_menu_remove_telegram\"" "\"$item_menu_remove_viber\"" "\"$item_menu_remove_virtualbox\"" "\"$item_menu_remove_whatsapp\"" "\"$item_menu_remove_wps\"" "\"$item_menu_remove_code\"" "\"$item_menu_remove_notepadplus\"" "\"$item_menu_remove_yandex\"" "\"$item_menu_remove_remina\"" "\"$item_menu_remove_xrdp\"" "\"$item_menu_remove_seahorse\"" "\"$exit_menu\"" "\"$exit_app\"")
