#!/bin/bash
# #---------------init for item_menu_information_install menu-------------------------------
export item_menu_install_finereader="FineReader"
export item_menu_install_1c="Установка 1с"
export item_menu_install_kaspersky="Антивирус Касперский"
export item_menu_install_dinfo_19="Имя пк на 19дюймов"
export item_menu_install_dinfo_22="Имя пк на 22дюймов"
export item_menu_install_crypto1290="Криптопро.v1290"
export item_menu_install_crypto1145="Криптопро.v1145"
export item_menu_install_workbench="Mysql Workbench"
export item_menu_install_xampp="Xampp(аналог OpenServer)"

export item_menu_install_unityhub="unityhub"
export item_menu_install_Anaconda="Anaconda"
export item_menu_install_art_editor="artweaver"
export item_menu_install_pdf_editor="master-pdf-editor"
export item_menu_install_edge="edge"
export item_menu_install_mypaint="mypaint"
export item_menu_install_onlyoffice="onlyoffice-desktopeditors"
export item_menu_install_pascalABC="pascalABC"
export item_menu_install_pinta="pinta"
export item_menu_install_pycharm="pycharm"
export item_menu_install_skype="skype"
export item_menu_install_sublime="sublime-text"
export item_menu_install_telegram="telegram"
export item_menu_install_viber="viber"
export item_menu_install_virtualbox="virtualbox"
export item_menu_install_whatsapp="whatsapp"
export item_menu_install_wps="wps-office"
export item_menu_install_code="code"
export item_menu_install_notepadplus="notepadplus"

export item_menu_install_yandex="yandex-browser-stable"
export item_menu_install_remina="remmina"
export item_menu_install_xrdp="xrdp"
export item_menu_install_seahorse="seahorse"
export item_menu_install_scan="fly-scan"
export item_menu_install_apps=( "\"$item_menu_install_finereader\"" "\"$item_menu_install_1c\"" "\"$item_menu_install_workbench\"" "\"$item_menu_install_Anaconda\"" "\"$item_menu_install_unityhub\"" "\"$item_menu_install_xampp\"" "\"$item_menu_install_kaspersky\""  "\"$item_menu_install_art_editor\"" "\"$item_menu_install_pdf_editor\""  "\"$item_menu_install_crypto1290\"" "\"$item_menu_install_crypto1145\""  "\"$item_menu_install_dinfo_19\"" "\"$item_menu_install_dinfo_22\"" "\"$item_menu_install_edge\"" "\"$item_menu_install_mypaint\"" "\"$item_menu_install_onlyoffice\"" "\"$item_menu_install_pascalABC\"" "\"$item_menu_install_pinta\"" "\"$item_menu_install_pycharm\"" "\"$item_menu_install_skype\"" "\"$item_menu_install_sublime\"" "\"$item_menu_install_telegram\"" "\"$item_menu_install_viber\"" "\"$item_menu_install_virtualbox\"" "\"$item_menu_install_whatsapp\"" "\"$item_menu_install_wps\"" "\"$item_menu_install_code\"" "\"$item_menu_install_notepadplus\"" "\"$item_menu_install_yandex\"" "\"$item_menu_install_remina\"" "\"$item_menu_install_xrdp\"" "\"$item_menu_install_seahorse\"" "\"$item_menu_install_scan\"" "\"$exit_menu\"" "\"$exit_app\"")
 
